### ISSUE TITLE
Paper?

### ISSUE THREAD

**Issue by baggepinnen** [dojo-sim/Dojo.jl#1]
Hey guys! Congratulations on this interesting package :) I'm just wondering how one can find the paper you're referring to in the readme, I'd be keen to read it!
Best regards,
Fredrik

**Comment by thowell** [comment]
@baggepinnen paper is submitted and will be up on arxiv by Friday!

**Comment by baggepinnen** [comment]
Thanks for paper and repo, I'm excited to try this out soon!
