### ISSUE TITLE
Purpose of `∂vector_rotate∂p`

### ISSUE THREAD

**Issue by rejuvyesh** [dojo-sim/Dojo.jl#16]
https://github.com/dojo-sim/Dojo.jl/blob/0d54f76c3458f2eb979af0feb368c9c7b270100e/src/orientation/rotate.jl#L7

I wasn't sure what this function is supposed to do here, but `p` is unused.

**Comment by thowell** [comment]
This method is unnecessary. It simply returns a rotation matrix for a given quaternion since `vector_rotate` is always linear in `p`. I think was useful as we derived expressions using chain rule, but we can remove this method and replace instances of it throughout the code.

**Comment by simon-lc** [comment]
I removed this function from the code. Thanks Jayesh for pointing this out!
