### ISSUE TITLE
Miss using FiniteDiff 

### ISSUE THREAD

**Issue by JSun950313** [dojo-sim/Dojo.jl#21]
https://github.com/dojo-sim/Dojo.jl/blob/ad046e5f6384d77684fba4e3616c981e0ed66c19/examples/trajectory_optimization/quadruped_min.jl#L38
When I ran this script, REPL reported an error that said FiniteDiff is undefined. I think the code missed using the package of FiniteDiff.

**Comment by thowell** [comment]
FiniteDiff is now added to examples dependencies. Thanks!
