### ISSUE TITLE
UndefVarError: gravity_compensation not defined

### ISSUE THREAD

**Issue by JSun950313** [dojo-sim/Dojo.jl#22]
https://github.com/dojo-sim/Dojo.jl/blob/ad046e5f6384d77684fba4e3616c981e0ed66c19/examples/trajectory_optimization/quadruped_min.jl#L64

I cannot find the code of this function and REPL report an error when I run it.

**Comment by thowell** [comment]
I think this method got lost during cleanup. I restored it here: https://github.com/dojo-sim/Dojo.jl/blob/main/environments/quadruped/methods/template.jl

**Comment by simon-lc** [comment]
I updated the gravity compensation function and ran it in the script:  quadruped_min.jl 
It should work now, so I am closing this issue. 
@JSun950313 feel free to reopen if you still experience some issues!
