### ISSUE TITLE
Error of using keyword arguments

### ISSUE THREAD

**Issue by JSun950313** [dojo-sim/Dojo.jl#25]
https://github.com/dojo-sim/Dojo.jl/blob/2727f5eb7264d19ec1bf02a318fdbb4da3c13e52/examples/simulation/tippetop.jl#L17
The keyword arguments of the function are body_position, body_orientation, body_linear_velocity, and body_angular_velocity. But keyword arguments in the script are x, θ, and ω. When I run this script, REPL reports an error.

**Comment by simon-lc** [comment]
Thanks Jia! I'll fix it today
