### ISSUE TITLE
hopper_min and hopper_max examples broken (?)

### ISSUE THREAD

**Issue by GlenHenshaw** [dojo-sim/Dojo.jl#26]
Julia 1.7.2 on macOS 12.3, Apple M1 architecture.

     julia> include("hopper_min.jl")
      Activating project at `~/.julia/packages/Dojo/frGnC/examples`
    ┌ Info: MeshCat server started. You can open the visualizer by visiting the following URL in your browser:
    └ http://127.0.0.1:8717
    ERROR: LoadError: UndefVarError: raiberthopper_nominal_max not defined
    Stacktrace:
     [1] top-level scope
       @ ~/.julia/packages/Dojo/frGnC/examples/trajectory_optimization/hopper_min.jl:26
     [2] include(fname::String)
       @ Base.MainInclude ./client.jl:451
     [3] top-level scope
       @ REPL[19]:1
    in expression starting at /Users/glenhenshaw/.julia/packages/Dojo/frGnC/examples/trajectory_optimization/hopper_min.jl:26

**Comment by simon-lc** [comment]
Thanks for the pointer! We're looking into this right now, it should be a quick fix.

**Comment by janbruedigam** [comment]
The actuated example was removed in the latest version, but the Raibert hopper mechanism still exists in case people want to write there own controller.
