### ISSUE TITLE
quadruped_min example broken (?)

### ISSUE THREAD

**Issue by GlenHenshaw** [dojo-sim/Dojo.jl#27]
Julia 1.7.2 on macOS 12.3, Apple M1 architecture

    julia> include("quadruped_min.jl")
          Activating project at `~/.julia/packages/Dojo/frGnC/examples`
        ┌ Info: MeshCat server started. You can open the visualizer by visiting the following URL in your browser:
        └ http://127.0.0.1:8719
        typeof(Z) = Vector{Float64}
        ┌ Warning: need to treat the joint to origin
        └ @ Main ~/.julia/packages/Dojo/frGnC/environments/quadruped/methods/template.jl:124
        ERROR: LoadError: UndefVarError: spring_impulses not defined
        Stacktrace:
         [1] gravity_compensation(mechanism::Mechanism{Float64, 38, 13, 13, 12})
           @ Main ~/.julia/packages/Dojo/frGnC/environments/quadruped/methods/template.jl:119
         [2] top-level scope
           @ ~/.julia/packages/Dojo/frGnC/examples/trajectory_optimization/quadruped_min.jl:64
         [3] include(fname::String)
           @ Base.MainInclude ./client.jl:451
         [4] top-level scope
           @ REPL[22]:1
        in expression starting at /Users/glenhenshaw/.julia/packages/Dojo/frGnC/examples/trajectory_optimization/quadruped_min.jl:64

**Comment by simon-lc** [comment]
Thanks for pointing this out!

**Comment by thowell** [comment]
This example will run now on main. The objective hasn't been re-tuned since we updated the joint friction model. I expect we improve this example in the next few days.

**Comment by janbruedigam** [comment]
Example was removed in the latest version. But there is a sampling-based learning example with the quadruped.
