### ISSUE TITLE
pendulum_max example broken (?)

### ISSUE THREAD

**Issue by GlenHenshaw** [dojo-sim/Dojo.jl#28]
Julia 1.7.2, macOS 12.3, Apple M1 architecture

        julia> include("pendulum_max.jl")
          Activating project at `~/.julia/packages/Dojo/frGnC/examples`
        ERROR: LoadError: UndefVarError: pendulum_nominal_max not defined
        Stacktrace:
         [1] top-level scope
           @ ~/.julia/packages/Dojo/frGnC/examples/trajectory_optimization/pendulum_max.jl:29
         [2] include(fname::String)
           @ Base.MainInclude ./client.jl:451
         [3] top-level scope
           @ REPL[26]:1
        in expression starting at /Users/glenhenshaw/.julia/packages/Dojo/frGnC/examples/trajectory_optimization/pendulum_max.jl:29

**Comment by simon-lc** [comment]
Thanks for pointing this out!

**Comment by janbruedigam** [comment]
Example was removed in the latest version. A few examples with (controlled) pendulums were added, however.
