### ISSUE TITLE
quadruped_min example still broken

### ISSUE THREAD

**Issue by GlenHenshaw** [dojo-sim/Dojo.jl#32]
julia> include("quadruped_min.jl")
          Activating project at `~/.julia/packages/Dojo/tpwPK/examples`
        ┌ Info: MeshCat server started. You can open the visualizer by visiting the following URL in your browser:
        └ http://127.0.0.1:8721
        typeof(Z) = Vector{Float64}
        ERROR: LoadError: UndefVarError: gravity_compensation not defined
        Stacktrace:
         [1] top-level scope
           @ ~/.julia/packages/Dojo/tpwPK/examples/trajectory_optimization/quadruped_min.jl:64
         [2] include(fname::String)
           @ Base.MainInclude ./client.jl:451
         [3] top-level scope
           @ REPL[8]:1
        in expression starting at /Users/glenhenshaw/.julia/packages/Dojo/tpwPK/examples/trajectory_optimization/quadruped_min.jl:64

**Comment by thowell** [comment]
I recommend adding `Dojo#main`. This will download the latest version of Dojo where we have fixed this issue.

**Comment by GlenHenshaw** [comment]
Done. That fixed this particular problem, thanks.
