### ISSUE TITLE
DojoEnvironments

### ISSUE THREAD

**Issue by thowell** [dojo-sim/Dojo.jl#36]
Is there a good way to breakout the environments from the primary simulator package while maintaining the integrity of tests across both packages? 
@rejuvyesh 
@janbruedigam

**Comment by rejuvyesh** [comment]
Yeah. You can even register packages in a subdirectory these days! Let me know if you need any help there.

**Comment by rejuvyesh** [comment]
Simplest would be to `dev` both the projects in the GitHub Action workflow and run the appropriate tests!
