### ISSUE TITLE
atlas_min and hopper_min don't converge

### ISSUE THREAD

**Issue by swami1995** [dojo-sim/Dojo.jl#41]
I was trying to run the examples in examples/trajectory_optimization/ but couldn't get the atlas example and the hopper example to converge.. (the hopper one at least was converging with the RL policy I was training but didn't have much luck with atlas there).. @thowell mentioned that the friction model was changed recently so the trajopt parameters might have to be tuned to get  it working again.

**Comment by janbruedigam** [comment]
The example was removed in the latest version, but the mechanism still exists so people can write their own versions.
