### ISSUE TITLE
Observation normalization is not equivalent for `distributed` vs `threaded`

### ISSUE THREAD

**Issue by rejuvyesh** [dojo-sim/Dojo.jl#5]
https://github.com/dojo-sim/Dojo.jl/blob/c513e78659de07fb930148b63989a8d5bfa72dd4/examples/reinforcement_learning/algorithms/ars.jl#L119-L127

The distributed version updates a different `normalizer` for each run. Not sure if that was intentional.

**Comment by janbruedigam** [comment]
I removed parallelization in this example in the latest version to keep the examples rather simple. Parallelization would be a nice feature but I think it might make more sense to put that in its own package or in ReinforcementLearning.jl. 
Feel free to reopen if you see it differently.
