### ISSUE TITLE
Defining a Mechanism Documentation out-of-date

### ISSUE THREAD

**Issue by mfogelson** [dojo-sim/Dojo.jl#58]
As a new person to Julia these were some problems I encountered while working through the documentation. 

When trying to create the Tippetop from the Documentation under "Defining a Mechanism" there are several functions that seem to be modified leading to errors and some information that could included for clarity: 

1) Dependencies are unclear
- Must add LinearAlgebra for new mechanism to access Diagonal function
- gray_light is not exported by Dojo.jl Available color functions: cyan, orange, magenta
- Must import Dojo.set_minimal_coordinates_velocities!

2) Simulation does not match video
- The default values for initialize_tippetop! do not generate the cool spinning video, it would be nice if those parameters were included in the documentation as well.

**Comment by janbruedigam** [comment]
The docs should be up to date now, although some of the videos might be different from the current code version.
Feel free to reopen if there are issues.
