### ISSUE TITLE
Reason for `MeshCat` compat bound to `v0.13`

### ISSUE THREAD

**Issue by rejuvyesh** [dojo-sim/Dojo.jl#6]
https://github.com/dojo-sim/Dojo.jl/blob/c513e78659de07fb930148b63989a8d5bfa72dd4/Project.toml#L38

For Julia v1.7 and later, we need StaticArrays v1.4 and later for some of the `lu` interface changes. But this conflicts with `MeshCat` v0.13 and requires updating to MeshCat v0.14. Locally updating MeshCat to v0.14 didn't seem to effect anything, but to be fair, I didn't look too hard.

**Comment by thowell** [comment]
I think we just need MeshCat +0.13.0. Will check a few cases then upgrade.

**Comment by thowell** [comment]
Thanks for updating these with #7
