### ISSUE TITLE
Error when accessing gradients in AGS

### ISSUE THREAD

**Issue by yesiam-png** [dojo-sim/Dojo.jl#63]
Hi,

Thanks for your excellent code! I'm new to julia. When I run the training code in `ags.jl` file (by changing the `ars` function in `ant_ars.jl` to `ags`), I get the error `ERROR: BoundsError: attempt to access 0-element UnitRange{Int64} at index [0]`, which traces back to this [line](https://github.com/dojo-sim/Dojo.jl/blob/main/src/gradients/state.jl#L162). Could anyone help me with this?

Ian

**Comment by janbruedigam** [comment]
The AGS example was removed in the latest version to keep the examples rather simple. A proper implementation of such algorithms should probably be in its own package.
