### ISSUE TITLE
Where can I find examples of atlas.jl

### ISSUE THREAD

**Issue by Seas00n** [dojo-sim/Dojo.jl#94]
I saw that the trajectory optimization on the official website has many Trajectory Optimization cases such as quadrupedal and atlas, but they seem to have been removed from the current warehouse. May I ask where can I find these cases

**Comment by janbruedigam** [comment]
The trajectory optimization examples were removed in the latest version due to some breaking changes, but the mechanisms still exists for people to create their own controlled version.
